### ISSUE TITLE
Doesn't seem to be joining channels

### ISSUE THREAD

**Issue by DanielOaks** [DanielOaks/gircbnc#10]
Hmm, it should probably do this, being an IRC bouncer and all. #6 related.

**Comment by prawnsalad** [comment]
Related; Should it also store new channels into the db when we receive JOIN events for ourselves? I'm thinking yes so that they can be re-joined on a reconnect.

**Comment by DanielOaks** [comment]
Yeah I think so as well (at the same time, it can also store the key we're given for the channel too).

**Comment by DanielOaks** [comment]
Resolved with an update to irc-go and cf1a98ca8bc6039afd89aae68f77ff0dda0433f5. I've marked adding channels to the db as a TODO in the relevant code.
