### ISSUE TITLE
Log query/channel messages to disk

### ISSUE THREAD

**Issue by DanielOaks** [DanielOaks/gircbnc#16]
ZNC separates it out by day by default. I'm wondering how specific we should get with it. We'll likely do something like a custom format so peeps can have it however they want, with a default of per-day.

**Comment by DanielOaks** [comment]
This will just be a simple writing lines to files thing, same as ZNC does. Config will likely be something like: enabled (bool), format (strong), root directory for logs (defaults to `./log` if no choice is made).

**Comment by prawnsalad** [comment]
This was part of https://github.com/goshuirc/bnc/issues/18
