### ISSUE TITLE
Store and replay query/channel message history

### ISSUE THREAD

**Issue by DanielOaks** [DanielOaks/gircbnc#17]
We should do this since this is a very basic, necessary feature of bouncers.

**Comment by DanielOaks** [comment]
This is just "someone sent a query to us when no clients were connected, replay it when a client joins" and "store+replay last ~50 lines of channel messages on a client joining". I'm gonna go very simple and basic with this just to have the functionality, and we'll work out how to take it later.

**Comment by prawnsalad** [comment]
This was part of https://github.com/goshuirc/bnc/issues/18
