### ISSUE TITLE
make different types of datastores possible using interfaces and similar

### ISSUE THREAD

**Issue by DanielOaks** [DanielOaks/gircbnc#40]
this just makes sense, cleanup how we're doing it, use interfaces all around the place instead of a specific buntdb datastore struct, etc.

**Comment by prawnsalad** [comment]
This has already been implemented and in use.

https://github.com/goshuirc/bnc/blob/master/bnc.go#L79
https://github.com/goshuirc/bnc/blob/master/lib/manager.go#L26
https://github.com/goshuirc/bnc/blob/master/lib/datastore.go

**Comment by DanielOaks** [comment]
Fair enough, shows me for not looking hard enough!
